name: Refresh metadata
on:
  workflow_dispatch:
  # push:
  #   branches:
  #     main
  # schedule:
  #   - cron: '0 */3 * * *'

jobs:
  refresh_metadata:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Fetch metadata
      run: |
        python app.py
    - name: Deploy 🚀
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.TOKEN }}
        user_name: Code for IATI bot
        user_email: 57559326+codeforIATIbot@users.noreply.github.com
        publish_dir: ./out
        enable_jekyll: true
        force_orphan: true
        allow_empty_commit: true
